- charts/adot-exporter-for-eks-on-ec2/templates/aws-for-fluent-bit/configmap.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
This PR is to resolve https://github.com/aws-observability/aws-otel-helm-charts/issues/7
Added a way to modify imds_version as a configurable value in values.yaml; defaults to v1
> Added an additional field to modify imds_version 

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
Release v0.2.0 of `adot-exporter-for-eks-on-ec2`
- update maintainers
- update collector version
- update app version to match collector
- update version
> Release v0.2.0

- README.md
Added ADOT roadmap link to readme.
> Updated readme and added roadmap link

- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:** Fixing a bug
**Link to tracking Issue:** #37 
> Added missing prometheus.io/port annotation value to scrape config

- .github/workflows/release.yaml
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>
> Fix branch name for release workflow

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
**Description:** Updates helm chart version to `v0.6.0` and upgrades app version to `v0.18.0`. Also updates `maintainer` filed in chart. 
> v0.6.0 helm chart release

- README.md
Adding Helm Chart repo name
**Description:** Documentation update to include the path of the Helm repo.
**Documentation:** 
Added Helm Chart repo path 
> Update README.md to include helm chart repository 

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/general-issue.md
- README.md
**Description:** Update issue template and readme to reflect GH support policy
> Add best effort support to README and Issue Template

- charts/adot-exporter-for-eks-on-ec2/README.md
**Description:** Fixed a typo in the readme
> Fixed Typo in Readme.md

- charts/adot-exporter-for-eks-on-ec2/templates/adot-collector/clusterrole.yaml
**Description:** <Describe what has changed.>
The ClusterRole is missing some attributes and cause the errors as above
**Link to tracking Issue:** <Issue number if applicable>
**Testing:** <Describe what testing was performed and which tests were added.>
**Documentation:** <Describe the documentation added.>
> Add missing rule in ClusterRole

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/templates/adot-collector/configmap.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:**
This PR updates collector version v0.22.0,
**Link to tracking Issue:** #68 
**Testing:** 
**Documentation:** <Describe the documentation added.>
> Upate Helm Chart to use v0.22.0- Helm chart release v0.8.0

- .github/workflows/stale-bot.yml
**Description:** 
This PR will create stale bot in the repo.
**Link to tracking Issue:** <Issue number if applicable>
**Testing:** <Describe what testing was performed and which tests were added.>
**Documentation:** <Describe the documentation added.>
> Create Stale bot in repo

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>
> Update collector version

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:** Update collector version to v0.25.0. update app version to v0.11.0
> Update collector and app version for v0.25.0

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:** Updated collector and app version for collector v0.26.0
> [chore] Update helm chart for collector v0.26.0

- README.md
> adds PR policy change

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:** Updated the collector and app version for collector v0.27.0
> Update helm chart for collector v0.27.0

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:** Updated the collector and app version for collector v0.28.0
> Chore: Update helm chart for collector v0.28.0

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:** Update to use ADOT collector v0.29.0
> Update to use ADOT collector v0.29.0

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:** 
Update ADOT Collector version to the latest release.
> Update ADOT Collector Version to v0.30.0

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:** Update ADOT Collector to v0.31.0
> Update adot collector version

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:** Update ADOT Collector version to v0.32.0.
> Update ADOT Collector version to v0.32.0

- charts/adot-exporter-for-eks-on-ec2/templates/adot-collector/daemonset.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:**
* add tolerations to adot exporter daemonset
* default adotcollector tolerations values to empty list
**Link to tracking Issue:** N/A
**Testing:** Was not tested
**Documentation:** No documentation needed
> add tolerations to adot exporter daemonset

- charts/adot-exporter-for-eks-on-ec2/values.schema.json
**Description:** 
Updates values.schema.json w.r.t to this [change](https://github.com/aws-observability/aws-otel-helm-charts/pull/45/files#diff-d4af7834dc7df71558cbcfc31b5c5fe600f3f597a9e18d4816720e11f224d7af)
> [chore] Change Values.schema to add tolerations

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:** Bump collector and chart version
> Bump chart version to v0.19.0

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:** Bump Helm chart version and ADOT Collector - v0.34.0
> Update Helm chart version and ADOT Collector - v0.34.0

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
**Description:** Update collector version to v0.35.0
> Update collector version to v0.35.0

- charts/adot-exporter-for-eks-on-ec2/Chart.yaml
- charts/adot-exporter-for-eks-on-ec2/values.yaml
> Bump collector version
